#index:
#    path: /
#    controller: App\Controller\DefaultController::index

about:
    path: /about/
    controller: App\Controller\AboutController::show
homepage:
    path:   /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController
    defaults:
        route: 'lesson_index'